# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DinoDataset": "Dino.ipynb",
         "predict_images": "Dino.ipynb",
         "ImgImporter": "ImgImporter.ipynb",
         "load_yaml": "lib.ipynb",
         "get_project_root": "lib.ipynb",
         "set_secrets": "lib.ipynb"}

modules = ["models/dino.py",
           "ImgImporter.py",
           "lib.py"]

doc_url = "https://willkunz13.github.io/synthetic_im/"

git_url = "https://github.com/willkunz13/synthetic_im/tree/main/"

def custom_doc_links(name): return None
