# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/lib.ipynb (unless otherwise specified).

__all__ = ['load_yaml', 'get_project_root', 'set_secrets']

# Cell
import yaml
import os
from pathlib import Path
def load_yaml(yfile:str):
    """Returns the data from a yaml file."""
    with open(yfile, 'r') as f:
        return yaml.safe_load(f)

# Cell

def get_project_root():
    return Path(__file__).parent.parent

# Cell
def set_secrets():
    secrets_fp = next(get_project_root().rglob('secrets.y*'))
    secrets = load_yaml(secrets_fp)
    for secret in secrets:
       os.environ[secret] = secrets[secret]