# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/lib.ipynb (unless otherwise specified).

__all__ = ['load_yaml']

# Cell
def load_yaml(yfile:str):
    """Returns the data from a yaml file."""
    with open(yfile, 'r') as f:
        return yaml.safe_load(f)